# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Niklas Sch채ffer - Software Engineer
description: "Die offizielle Internet-Pr채senz von Niklas Sch채ffer"
keywords: "development, web, laravel, zend"
url: http://schaeffer.it
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/niklasschaeffer/schaeffer.it
disqus_shortname: "schaefferit"
disqus_site_shortname: "schaefferit"

# Author settings
author:
  name      : Niklas Sch채ffer
  job       : Software Engineer
  bio       : "Enthusiastische Performance, Responsives Design und Usability, immer auf der Suche nach dem besten Projekt und gutem Kaffee."
  thumb     : /images/author.jpg
  email     : niklas@schaeffer.it
  url       : http://schaeffer.it
  github    : http://github.com/niklasschaeffer
  twitter   : http://twitter.com/niklasschaeffer
  facebook  : http://facebook.com/wildrelaxo
  linkedin  : https://de.linkedin.com/in/niklasschaeffer

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog
  - slug: projects
    title: Projects

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]